apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo
  namespace: django-app
spec:
  replicas: 2
  selector:
    matchlabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      -name: todo
      image: rohit8329/django-app:latest
      ports:
      - containerPort: 8000
