apiVersion: v1
kind: Service
metadata:
  name: django-todo-services
  namespace: python-django-app
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 30007

# for Cluster IP print new line after targetPort.
# type: ClusterIP

# for Loadbalancer print new line after targetPort
# type: Loadbalancer