pipeline{
    agent any
    stages{
        stage('Code'){
            steps{
                git url : "https://github.com/Rohit312001/node-todo-cicd.git", branch : "master"
            }
        }
        stage('Build'){
            agent{
                docker{
                    image 'todo-node-app'
                    reuseNode true
                }
            }
                steps {
                    echo "Building code"
                    sh 'node --version'
                }
        }
        stage('Test'){
            steps{
                echo "Testing"
            }
        }
        stage('Deploy'){
            steps{
                sh 'docker run -d --name node-todo-app -p 8000:8000 todo-node-app'
            }
        }
    }
}